version : "3.8"
services:
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    restart:  always
    ports: 
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart:  always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

  app:
    build: 
      context: ./backend    # Django uygulamanızın bulunduğu dizin
    volumes:
      - ./backend:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 myapp.wsgi:application  # Gunicorn ile çalıştırma
    # command: gunicorn --bind 0.0.0.0:8000 myapp.wsgi:application -w 1 # 1 worker with the -w flag for low trafic
    depends_on:
      - db
      - redis
    # image: mysql
    # volumes:
    #   - ./data/mysql/db:/var/lib/mysql
    # environment:
    #   - MYSQL_DATABASE= 'django-app-db'
    #   - MYSQL_ALLOW_EMPTY_PASSWORD= 'true'

  celery:
    restart: always
    build: 
      context: ./backend    # Django uygulamanızın bulunduğu dizin
    command: celery -A myapp worker -l INFO # INFO or DEBUG
    volumes:
      - ./backend:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app
      
  frontend:
    container_name: nextjs_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - app

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/django
    depends_on:
      - app
    container_name: nginx