# Generated by Django 5.1.7 on 2025-03-18 19:08

import streamfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default=list, verbose_name='Page blocks'),
        ),
    ]
