# Generated by Django 5.1.7 on 2025-03-18 19:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stream_json',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
