# Generated by Django 5.1.7 on 2025-03-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_stream_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='stream_json',
        ),
    ]
