# Generated by Django 5.1.7 on 2025-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='stream',
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
