# Generated by Django 5.1.7 on 2025-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='folder/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image with text',
                'verbose_name_plural': 'Images with text',
            },
        ),
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Text',
            },
        ),
    ]
