"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import Config,Csv, RepositoryEnv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect environment (default to 'local' if not set)
ENVIRONMENT = os.getenv('DJANGO_ENV', 'local')

# Define env file path based on environment
env_file =  f".env.{ENVIRONMENT}"

# Check if the environment file exists before trying to load it
if not os.path.exists(env_file):
    raise FileNotFoundError(f"The environment file {env_file} does not exist. Please create it.")

# Load the specified environment file
config = Config(RepositoryEnv(env_file))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
# CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_celery_beat",
    "django_celery_results",
    'storages',
    'corsheaders',
    'django_filters',
    'rest_framework',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    'core',

    'users'
]

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",  # Add this line
    'django.middleware.security.SecurityMiddleware',
    "myapp.middleware.SecurityHeadersMiddleware",  # Add custom security headers middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'myapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DB_NAME', default=BASE_DIR / 'db.sqlite3'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'tr-TR'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Define STATIC and MEDIA settings
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Additional locations of static files (Only for local & S3)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STORAGE_BACKEND = config('STORAGE_BACKEND', default="local")
STORAGES = {
    "default": {},  # Will be set dynamically
    "staticfiles": {},  # Will be set dynamically
}

if STORAGE_BACKEND == "s3":
    # Use S3 for both media and static files
    STORAGES["default"]["BACKEND"] = "storages.backends.s3.S3Storage"
    STORAGES["staticfiles"]["BACKEND"] = "storages.backends.s3.S3Storage"

    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default="eu-north-1")
    AWS_S3_SIGNATURE_VERSION = 's3v4'

    AWS_QUERYSTRING_AUTH = False  # Public URLs for static/media files
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Optimize caching
    }
    AWS_CUSTOM_DOMAIN = f'{config('AWS_STORAGE_BUCKET_NAME')}.amazonaws.com/'
    AWS_DEFAULT_ACL = None  # Avoids issues with public/private access
    AWS_S3_FILE_OVERWRITE = False  # Prevents overwriting files with same name

    STATICFILES_DIRS = []  # Avoid duplicate static file handling

elif STORAGE_BACKEND == "whitenoise":
    # Use WhiteNoise for static, local for media. Production (Heroku, Docker)
    STORAGES["default"]["BACKEND"] = "django.core.files.storage.FileSystemStorage"
    STORAGES["staticfiles"]["BACKEND"] = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    WHITENOISE_RUNSERVER_NOSTATIC = True  # Prevents Django’s dev server from interfering with WhiteNoise
    STATICFILES_DIRS = []  # Avoid duplicate static file handling

else:  # Default: Local file system storage (Nginx setup)
    STORAGES["default"]["BACKEND"] = "django.core.files.storage.FileSystemStorage"
    STORAGES["staticfiles"]["BACKEND"] = "django.contrib.staticfiles.storage.StaticFilesStorage"

    # No need to override STATIC_ROOT and MEDIA_ROOT again
    # They are already set globally 
    STATIC_ROOT = config('STATIC_ROOT')   # Make sure this is correct
    MEDIA_ROOT = config('MEDIA_ROOT')  # Make sure this is correct


# Set file upload permissions globally (applies to all storage types)
FILE_UPLOAD_PERMISSIONS = 0o644  # Ensures uploaded files are readable by web server

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#REST FRAMEWORK

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        'rest_framework.permissions.IsAuthenticated'
    ],
     'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 'EXCEPTION_HANDLER': 'app.utils.custom_exception_handler',
  
}

from datetime import timedelta 

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True



# Default email backend setting
DEFAULT_EMAIL_BACKEND = config('DEFAULT_EMAIL_BACKEND', default='smtp')

# Email configuration based on the selected backend
if DEFAULT_EMAIL_BACKEND == 'mailjet':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('MAILJET_EMAIL_HOST', default='in-v3.mailjet.com')
    EMAIL_PORT = config('MAILJET_EMAIL_PORT', 587)
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('MAILJET_API_KEY')
    EMAIL_HOST_PASSWORD = config('MAILJET_SECRET_KEY')
    EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = 30

elif DEFAULT_EMAIL_BACKEND == 'mailgun':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('MAILGUN_EMAIL_HOST', default='smtp.mailgun.org')
    EMAIL_PORT = config('MAILGUN_EMAIL_PORT', 587)
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('MAILGUN_SMTP_LOGIN')
    EMAIL_HOST_PASSWORD = config('MAILGUN_SMTP_PASSWORD')

elif DEFAULT_EMAIL_BACKEND == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('SMTP_EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('SMTP_EMAIL_PORT', 587)
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('SMTP_EMAIL_USER')
    EMAIL_HOST_PASSWORD = config('SMTP_EMAIL_PASSWORD')

elif DEFAULT_EMAIL_BACKEND == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

else:
    raise ValueError(f"Unsupported email backend: {DEFAULT_EMAIL_BACKEND}")






# Auto-reconnect on startup
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Adjust settings based on DEBUG
if DEBUG:
    # Development settings (run tasks locally, no need for concurrency)
    CELERY_BROKER_URL="sqla+sqlite:///celerydb.sqlite3"
    CELERY_RESULT_BACKEND="django-db"
    CELERY_TASK_ALWAYS_EAGER = True  # Runs tasks locally
    CELERYD_POOL = 'solo'  # For Windows, avoids multiprocessing (development only)
else:
    # Production settings (tasks are processed asynchronously in the background)
    CELERY_BROKER_URL= config("CELERY_BROKER_REDIS_URL", default="redis://localhost:6379")
    CELERY_RESULT_BACKEND= config("CELERY_BROKER_REDIS_URL", default="redis://localhost:6379")
    CELERY_TASK_ALWAYS_EAGER = False  # Tasks run asynchronously
    CELERYD_POOL = 'prefork'  # Default pool for production (can handle concurrency)
    
    # Optionally, configure Celery Beat (task scheduler) in production
    CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'











# Allow scripts and styles only from the same origin and specific sources
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "cdnjs.cloudflare.com", "'unsafe-inline'")  # Allow inline scripts cautiously
CSP_STYLE_SRC = ("'self'", "fonts.googleapis.com", "'unsafe-inline'")  # Allow inline styles cautiously
CSP_IMG_SRC = ("'self'", "data:", "cdn.example.com")  # Allow images from your domain and CDNs
CSP_FONT_SRC = ("'self'", "fonts.gstatic.com")
CSP_CONNECT_SRC = ("'self'", "api.example.com")  # Allow AJAX/WS connections to this domain
CSP_FRAME_SRC = ("'none'",)  # Disallow embedding in iframes
CSP_OBJECT_SRC = ("'none'",)  # Disallow Flash and other embedded objects
CSP_MEDIA_SRC = ("'self'",)


# Allow Alpine.js & HTMX if using them
CSP_SCRIPT_SRC += ("'unsafe-eval'",)  # Required for Alpine.js dynamic features
CSP_REPORT_URI = "/csp-report/"  # Endpoint to capture CSP violation reports


if not DEBUG:
    # Enforce HTTPS connections
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP traffic to HTTPS
    SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for one year (recommended)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to subdomains
    SECURE_HSTS_PRELOAD = True  # Allow browser preload list (optional)

    # Prevent MIME-type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True  

    # Prevent clickjacking attacks
    X_FRAME_OPTIONS = "DENY"  # Options: DENY, SAMEORIGIN

    # Enable browser XSS protection
    SECURE_BROWSER_XSS_FILTER = True  

    # Referrer Policy
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"  

    # Permissions Policy (limits access to browser features)
    PERMISSIONS_POLICY = {
        "geolocation": "self",
        "microphone": "none",
        "camera": "none",
        "fullscreen": "self",
    }